-- "자료표": a lightweight Excel-like CRUD table per project. User-defined columns, ordered rows of
-- cell values, both stored as JSON text (H2 TEXT is a CLOB alias, so this is identical on both engines).
-- No formulas/cell references - this is a data grid, not a spreadsheet engine. An optional password
-- (bcrypt, same PasswordEncoder bean as account login) gates opening/editing a given file beyond
-- normal project membership; the hint is stored in the clear since its whole purpose is to be shown
-- back to whoever is locked out, which necessarily weakens the password it is a hint for.
CREATE TABLE spreadsheet_file (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  owner_id BIGINT NOT NULL REFERENCES app_user(id),
  columns_json TEXT NOT NULL,
  password_hash VARCHAR(200),
  password_hint VARCHAR(300),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_spreadsheet_file_project ON spreadsheet_file(project_id);

CREATE TABLE spreadsheet_row (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_id BIGINT NOT NULL REFERENCES spreadsheet_file(id) ON DELETE CASCADE,
  row_order INT NOT NULL,
  cells_json TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_spreadsheet_row_file ON spreadsheet_row(file_id, row_order);
