CREATE TABLE organization_department (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization_team (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_id BIGINT NOT NULL,
  name VARCHAR(200) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_org_team_department FOREIGN KEY (department_id) REFERENCES organization_department(id),
  CONSTRAINT uq_org_team_name UNIQUE (department_id, name)
);

ALTER TABLE app_user ADD COLUMN department_id BIGINT;
ALTER TABLE app_user ADD COLUMN team_id BIGINT;
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_department FOREIGN KEY (department_id) REFERENCES organization_department(id);
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_team FOREIGN KEY (team_id) REFERENCES organization_team(id);
