package com.hub.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ConnectorRepositoryVisibilityTest {
    private JdbcTemplate jdbc;
    private ConnectorRepository repository;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:connector-visible-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        repository = new ConnectorRepository(jdbc);

        jdbc.execute("""
                CREATE TABLE document(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  project_id BIGINT NOT NULL,
                  source_type VARCHAR(40),
                  source_identifier VARCHAR(1000),
                  archived BOOLEAN NOT NULL DEFAULT FALSE,
                  source_deleted BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbc.execute("""
                CREATE TABLE external_item(
                  id BIGINT PRIMARY KEY,
                  project_id BIGINT NOT NULL,
                  connector_account_id BIGINT,
                  external_id VARCHAR(1000) NOT NULL,
                  item_type VARCHAR(60),
                  title VARCHAR(1000),
                  content CLOB,
                  author VARCHAR(500),
                  source_url VARCHAR(2000),
                  source_created_at TIMESTAMP,
                  raw_metadata CLOB,
                  imported_document_id BIGINT,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """);
        jdbc.execute("CREATE UNIQUE INDEX uq_external_item_project_external ON external_item(project_id,external_id)");
    }

    @Test
    void archivedConnectorDocumentHidesItsSnapshotFromEveryRetrievalPath() {
        jdbc.update("INSERT INTO external_item(id,project_id,external_id,item_type,title,content,author) VALUES(1,10,'GITHUB:repo:item-1','GIT_ISSUE','숨긴 자료','secret release plan','Alice')");
        jdbc.update("INSERT INTO external_item(id,project_id,external_id,item_type,title,content,author) VALUES(2,10,'GITHUB:repo:item-2','GIT_ISSUE','보이는 자료','secret public note','Alice')");
        jdbc.update("INSERT INTO document(id,project_id,source_type,source_identifier,archived,source_deleted) VALUES(101,10,'GITHUB','GITHUB:repo:item-1',TRUE,FALSE)");
        jdbc.update("INSERT INTO document(id,project_id,source_type,source_identifier,archived,source_deleted) VALUES(102,10,'GITHUB','GITHUB:repo:item-2',FALSE,FALSE)");

        assertEquals(List.of("GITHUB:repo:item-2"),
                repository.search(10, "secret", 20).stream().map(ConnectorRepository.ExternalSearchRow::externalId).toList());
        assertTrue(repository.searchByExactTitle(10, "숨긴 자료", 20).isEmpty());
        assertTrue(repository.searchByTitlePatterns(10, List.of("*숨긴*"), 20).isEmpty());
        assertEquals(List.of("GITHUB:repo:item-2"),
                repository.searchByMetadata(10, "Alice", null, null, Set.of("GITHUB"), 20).stream()
                        .map(ConnectorRepository.ExternalSearchRow::externalId).toList());
        assertTrue(repository.findByExternalId(10, "GITHUB:repo:item-1").isEmpty());
    }

    @Test
    void snapshotUpsertUsesProjectAndExternalIdAcrossDifferentConnectorAccounts() {
        repository.saveImportedItem(
                10L, 501L, "GITHUB", "repo:item-9", "GIT_ISSUE",
                "첫 제목", "첫 내용", "Alice", "https://example.test/1", null, "{}", 101L
        );
        repository.saveImportedItem(
                10L, 777L, "GITHUB", "repo:item-9", "GIT_ISSUE",
                "최신 제목", "최신 내용", "Bob", "https://example.test/2", null, "{}", 102L
        );

        assertEquals(1, jdbc.queryForObject(
                "SELECT COUNT(*) FROM external_item WHERE project_id=10 AND external_id='GITHUB:repo:item-9'",
                Integer.class));
        assertEquals(777L, jdbc.queryForObject(
                "SELECT connector_account_id FROM external_item WHERE project_id=10 AND external_id='GITHUB:repo:item-9'",
                Long.class));
        assertEquals(102L, jdbc.queryForObject(
                "SELECT imported_document_id FROM external_item WHERE project_id=10 AND external_id='GITHUB:repo:item-9'",
                Long.class));
        assertEquals("최신 내용", jdbc.queryForObject(
                "SELECT content FROM external_item WHERE project_id=10 AND external_id='GITHUB:repo:item-9'",
                String.class));
    }

    @Test
    void retentionKeepsLinkedSharedSnapshotAndRemovesOnlyTrulyUnlinkedRows() {
        jdbc.update("""
                INSERT INTO external_item(
                  id,project_id,connector_account_id,external_id,item_type,title,content,imported_document_id,created_at
                ) VALUES(20,10,NULL,'GITHUB:repo:linked','GIT_ISSUE','연결됨','keep',101,DATEADD('MONTH',-18,CURRENT_TIMESTAMP))
                """);
        jdbc.update("""
                INSERT INTO external_item(
                  id,project_id,connector_account_id,external_id,item_type,title,content,imported_document_id,created_at
                ) VALUES(21,10,NULL,'GITHUB:repo:orphan','GIT_ISSUE','미연결','remove',NULL,DATEADD('MONTH',-18,CURRENT_TIMESTAMP))
                """);

        assertEquals(1, repository.purgeOrphanedItemsOlderThan(java.time.LocalDate.now().minusMonths(12)));
        assertEquals(1, jdbc.queryForObject("SELECT COUNT(*) FROM external_item WHERE id=20", Integer.class));
        assertEquals(0, jdbc.queryForObject("SELECT COUNT(*) FROM external_item WHERE id=21", Integer.class));
    }
}
