package com.hub.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ConnectorRepositorySyncOwnerTest {
    private JdbcTemplate jdbc;
    private ConnectorRepository repository;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:connector-owner-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        repository = new ConnectorRepository(jdbc);
        jdbc.execute("""
                CREATE TABLE connector_sync_state(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  project_id BIGINT NOT NULL,
                  connector_type VARCHAR(30) NOT NULL,
                  external_scope VARCHAR(1000) NOT NULL,
                  owner_user_id BIGINT,
                  last_synced_at TIMESTAMP,
                  last_status VARCHAR(30),
                  last_error VARCHAR(1000),
                  last_imported_count INTEGER NOT NULL DEFAULT 0,
                  UNIQUE(project_id,connector_type,external_scope)
                )
                """);
    }

    @Test
    void scopeKeepsExactOwnerAndCanBeReboundOnlyByManualImport() {
        repository.saveSyncState(10L, "GITHUB", "repo-a", 7L, "SUCCESS", null, 3);
        List<ConnectorRepository.SyncScope> first = repository.allKnownScopes();

        assertEquals(1, first.size());
        assertEquals(7L, first.get(0).ownerUserId());

        repository.saveSyncState(10L, "GITHUB", "repo-a", 9L, "SUCCESS", null, 4);
        assertEquals(9L, repository.allKnownScopes().get(0).ownerUserId());
    }

    @Test
    void clearedOwnerStopsAutoSyncWorklist() {
        repository.saveSyncState(10L, "GITHUB", "repo-a", 7L, "SUCCESS", null, 3);
        assertEquals(1, repository.clearSyncOwnersForUser(7L));
        assertTrue(repository.allKnownScopes().isEmpty());
    }
}
