package com.hub.repository;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SearchLogRepositoryPrivacyTest {
    private JdbcTemplate jdbc;
    private SearchLogRepository repository;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:search-log-private-" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        repository = new SearchLogRepository(jdbc);
        jdbc.execute("""
                CREATE TABLE search_log(
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  project_id BIGINT NOT NULL,
                  user_id BIGINT NOT NULL,
                  query_text VARCHAR(1000) NOT NULL,
                  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
    }

    @Test
    void frequentSearchesDoNotLeakAcrossProjectMembers() {
        repository.log(9L, 11L, "내 계약 검토");
        repository.log(9L, 11L, "내 계약 검토");
        repository.log(9L, 22L, "인사 조정");
        repository.log(9L, 22L, "인사 조정");
        repository.log(9L, 22L, "인사 조정");

        List<Map<String,Object>> user11 = repository.topForUser(9L, 11L);
        List<Map<String,Object>> user22 = repository.topForUser(9L, 22L);

        assertEquals(List.of("내 계약 검토"), user11.stream().map(row -> String.valueOf(row.get("QUERY_TEXT"))).toList());
        assertEquals(List.of("인사 조정"), user22.stream().map(row -> String.valueOf(row.get("QUERY_TEXT"))).toList());
    }
}
