CREATE TABLE project_search_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL,
  aliases_json CLOB NOT NULL,
  patterns_json CLOB NOT NULL,
  target_file VARCHAR(500),
  mode VARCHAR(20) NOT NULL DEFAULT 'SMART' CHECK (mode IN ('SMART','FULL')),
  priority INT NOT NULL DEFAULT 100,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NOT NULL REFERENCES app_user(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_project_search_rule_project ON project_search_rule(project_id, active, priority DESC);

ALTER TABLE document_version ADD COLUMN embedding_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE document_version ADD COLUMN embedding_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE document_version ADD COLUMN embedding_last_error CLOB;
ALTER TABLE document_version ADD COLUMN embedding_updated_at TIMESTAMP;
UPDATE document_version v
SET embedding_status='READY', embedding_updated_at=CURRENT_TIMESTAMP
WHERE EXISTS (
  SELECT 1 FROM document_chunk c
  WHERE c.version_id=v.id AND c.embedding_json IS NOT NULL
);
CREATE INDEX idx_document_version_embedding_retry ON document_version(embedding_status, embedding_attempts, id);
