-- Files people attach to a todo, or send directly to a teammate. todo_id uses ON DELETE SET NULL so the
-- todo retention cleanup (old DONE todos) never destroys an attachment's file or metadata - only the
-- todo link is cleared, matching how todos already reference documents without owning their lifecycle.
CREATE TABLE file_attachment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  todo_id BIGINT REFERENCES todo(id) ON DELETE SET NULL,
  sender_id BIGINT NOT NULL REFERENCES app_user(id),
  recipient_id BIGINT REFERENCES app_user(id),
  file_name VARCHAR(500) NOT NULL,
  content_type VARCHAR(200),
  size_bytes BIGINT NOT NULL,
  storage_path VARCHAR(2000) NOT NULL,
  note VARCHAR(1000),
  read_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_file_attachment_todo ON file_attachment(todo_id);
CREATE INDEX idx_file_attachment_project_recipient ON file_attachment(project_id, recipient_id);
CREATE INDEX idx_file_attachment_project_sender ON file_attachment(project_id, sender_id);
