CREATE TABLE admin_submission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL REFERENCES app_user(id),
  title VARCHAR(500) NOT NULL,
  note VARCHAR(1000),
  external_url VARCHAR(2000),
  file_name VARCHAR(500),
  content_type VARCHAR(200),
  size_bytes BIGINT,
  storage_path VARCHAR(2000),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_admin_submission_project ON admin_submission(project_id, id);
CREATE INDEX idx_admin_submission_sender ON admin_submission(sender_id, id);
